# Generated by Django 4.0.3 on 2022-04-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='product',
            name='relative_product',
        ),
        migrations.AddField(
            model_name='product',
            name='relative_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.DeleteModel(
            name='RelativeProduct',
        ),
    ]
