# Generated by Django 4.0.3 on 2022-03-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name_alter_ingredient_made_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relativeproduct',
            name='name',
        ),
    ]
