# Generated by Django 4.0.3 on 2022-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_relativeproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(related_name='products', through='products.ProductAllergen', to='products.allergen'),
        ),
    ]
