# Generated by Django 4.0.3 on 2022-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergenstatuses',
            field=models.ManyToManyField(related_name='products', through='products.ProductAllergen', to='products.allergenstatus'),
        ),
    ]
