# Generated by Django 4.0.3 on 2022-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_allergenstatuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='allergen',
            name='allergens',
            field=models.ManyToManyField(related_name='products', through='products.ProductAllergen', to='products.allergen'),
        ),
    ]
