# Generated by Django 4.0.3 on 2022-04-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_allergens_allergen_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='allergens',
        ),
    ]
