# Generated by Django 4.0.3 on 2022-04-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_allergen_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergenstatuses',
        ),
        migrations.AddField(
            model_name='allergen',
            name='allergenstatuses',
            field=models.ManyToManyField(related_name='allergens', through='products.ProductAllergen', to='products.allergenstatus'),
        ),
    ]
